### ISSUE TITLE
Updating to the latest version caused some strange issues on my end (Firefox)

### ISSUE THREAD

**Issue by LOuroboros** [simonfrey/faster-pageload-web-extensions#14]
Hi. I've been using this addon for a while, and earlier today I updated it from the about:addons section of my copy of Mozilla Firefox.
Ever since I updated the addon, the web based client of Discord has been reloading whenever I try to change servers, and there's instances of dropdown menus in places like the old mobile Reddit dissappearing upon clicking.
These 2 issues both are fixed by disabling Faster Pageload, so I assume it has something to do with one of its most recent changes.
I use Mozilla Firefox ESR 78 x86, in case that matters.

If there's any other information I can provide, let me know.

**Comment by simonfrey** [comment]
Thank you for reporting that! @CactiChameleon9 could that have anything todo with the blacklist feature?

**Comment by CactiChameleon9** [comment]
I'm not sure, I can't think of what could cause it?

**Comment by CactiChameleon9** [comment]
@LOuroboros could you test on a new profile (about:profiles) ?

**Comment by simonfrey** [comment]
Aarg. It's me being a stupid. It's the same problem as https://github.com/simonfrey/faster-pageload-web-extensions/issues/11 with the instant page script in v5 being buggy. 

I reverted it ti v3 but never commited the change. Thereby reintroduced the problems with the update again. Will be fixed in a few mins
